site_name: Документация на продукт

nav:
  - Руководство по установке:
    - ig/index.md
    - Создание репозитория:
      - ig/repo__creation__gh.md
      - ig/repo__creation__gl.md
    - ig/mkdocs__installation.md
  - Руководство администратора:
    - ag/index.md
    - ag/setup.md
    - ag/pub__setup.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo_fav.png
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Ночь
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: День
  features:
    - navigation.instant # ускорение загрузки (SPA)
    - navigation.tracking # динамический URL страницы 
    - navigation.tabs # верхний уровень заголовков в горизонтальное меню
    - navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
    - navigation.indexes # главные страницы разделов не отображаются в меню
    - navigation.top # вкл. кнопку возврата наверх
    - content.action.edit # вкл. редактирование страницы


plugins: 
  - search:
      lang:
        - en
        - ru
